import { supabase, fireWebhook } from './supabase'
import { GENERATION_ENABLED, VIDEO_GENERATION_ENABLED } from './content'
import type { StudioSourceKind, StudioCopy } from './studio'
import type { CarouselSlide, RenderProgress } from './carousels'
import type { AspectRatio } from './studioStyles'

// Re-exported so page code can import everything Video Studio needs from one module, same as
// carousels.ts does for CarouselStudio.tsx.
export { describeProgress, overallProgress } from './carousels'
export type { CarouselSlide, RenderProgress } from './carousels'

export type VideoJobStatus = 'drafting' | 'draft_ready' | 'rendering' | 'done' | 'failed'
export type VideoType = 'motion_graphics' | 'generated_clips'

export const VIDEO_ENGINES = ['veo-3.1-lite', 'veo-3.1-fast', 'veo-3.1-standard'] as const
export type VideoEngine = (typeof VIDEO_ENGINES)[number]

export const VIDEO_RESOLUTIONS = ['720p', '1080p', '4k'] as const
export type VideoResolution = (typeof VIDEO_RESOLUTIONS)[number]

export const ENGINE_LABEL: Record<VideoEngine, string> = {
  'veo-3.1-lite': 'Veo 3.1 Lite',
  'veo-3.1-fast': 'Veo 3.1 Fast',
  'veo-3.1-standard': 'Veo 3.1 Standard',
}

/** What each tier is actually for, shown under the picker so the choice is about outcome rather
 *  than model trivia — same framing as AI Studio's model registry. */
export const ENGINE_BLURB: Record<VideoEngine, string> = {
  'veo-3.1-lite': 'Cheapest. Good for abstract, macro and texture work.',
  'veo-3.1-fast': 'Best balance — the sensible default for most posts.',
  'veo-3.1-standard': 'Highest fidelity, ~3x Fast. Short single shots only.',
}

/**
 * Real per-second pricing by engine and resolution, confirmed against
 * ai.google.dev/gemini-api/docs/pricing (2026-09-08). Lite and Fast get genuinely cheaper at
 * 720p; Standard charges the same for 720p and 1080p. `null` means that tier doesn't offer that
 * resolution at all (Lite has no 4K), and the pickers grey it out rather than guessing.
 *
 * Duplicated in carousel-studio/veo.js and the ScalePods · Video Brief workflow — three places
 * with no shared build step between them, kept in sync by hand, same convention this project
 * already uses for TARGET_DIMENSIONS. This copy drives the FE estimate; the worker's copy is
 * what actually bills.
 */
export const PRICE_PER_SECOND: Record<VideoEngine, Record<VideoResolution, number | null>> = {
  'veo-3.1-lite': { '720p': 0.05, '1080p': 0.08, '4k': null },
  'veo-3.1-fast': { '720p': 0.10, '1080p': 0.12, '4k': 0.30 },
  'veo-3.1-standard': { '720p': 0.40, '1080p': 0.40, '4k': 0.60 },
}

/** Hard per-video spend ceiling (PRD §8's proposed default, locked 2026-09-08). The generate
 *  button is disabled above this, not just warned — "structurally impossible, not just
 *  unlikely" is the PRD's own bar. */
export const PER_VIDEO_CEILING_USD = 5

/** Mid-market rate as of 2026-09-08 (wise.com). Only ever used to render an INR figure alongside
 *  the USD one — every real charge is in USD, so this is a courtesy conversion, not an
 *  authoritative amount. Update by hand; being a few percent stale is harmless here. */
export const USD_TO_INR = 94.6

export function formatUsdInr(usd: number): string {
  return `$${usd.toFixed(2)} (≈₹${Math.round(usd * USD_TO_INR).toLocaleString('en-IN')})`
}

export function ratePerSecond(engine: VideoEngine, resolution: VideoResolution): number | null {
  return PRICE_PER_SECOND[engine][resolution]
}

export interface VideoShot {
  index: number
  prompt: string
  /** Burned into the video by the worker's ffmpeg drawtext pass — NOT generated by Veo, which
   *  cannot spell reliably. Optional; empty means this shot carries no words. */
  onScreenText?: string
  /** Per-shot negative prompt, per Google's own guidance that specific exclusions beat vague
   *  ones. Sent to Veo alongside the prompt. */
  negativePrompt?: string
  durationS: 4 | 6 | 8
  status: 'pending' | 'generating' | 'done' | 'failed'
  clipUrl: string | null
  costUsd: number | null
  errorDetail?: string | null
}

/** Cost of a shot list at a given engine+resolution. Uses each shot's REAL recorded cost once it
 *  has one, so the same function serves as both the pre-spend estimate (all shots pending) and
 *  the after-the-fact actual (shots generated) — same dual role AI Studio's cost helpers play. */
export function estimateShotsCost(
  engine: VideoEngine,
  resolution: VideoResolution,
  shots: VideoShot[],
): number {
  const rate = ratePerSecond(engine, resolution) ?? 0
  const total = shots.reduce((sum, s) => sum + (s.costUsd ?? s.durationS * rate), 0)
  return Math.round(total * 100) / 100
}

export function totalDurationS(shots: VideoShot[]): number {
  return shots.reduce((sum, s) => sum + s.durationS, 0)
}

/**
 * Turns a worker-written `error_detail` into something a human can act on.
 *
 * The worker tags known-recoverable failures with a machine-readable prefix (see
 * carousel-studio/veo.js's `classifyVeoError`) precisely so the FE doesn't have to pattern-match
 * raw Google error text — the most important case being a billing/quota failure, where the fix
 * is a specific action on a specific page rather than "try again".
 */
export interface VideoJobError {
  title: string
  detail: string
  /** Where the user should go to fix it, when there is such a place. */
  actionUrl?: string
  actionLabel?: string
}

export function describeVideoError(raw: string | null | undefined): VideoJobError | null {
  if (!raw) return null
  const text = String(raw)

  if (text.startsWith('QUOTA_EXCEEDED:') || /RESOURCE_EXHAUSTED|quota|billing|out of credits|insufficient/i.test(text)) {
    return {
      title: 'Google AI Studio is out of credits or over quota',
      detail:
        'Veo rejected the request because the connected Google account has no available credit or has hit its quota. Nothing was charged and no video was generated. Add credit or raise the quota, then run this again.',
      actionUrl: 'https://aistudio.google.com/app/plan_information',
      actionLabel: 'Add credits in Google AI Studio',
    }
  }
  if (text.startsWith('AUTH_FAILED:') || /API key|API_KEY_INVALID|PERMISSION_DENIED|unauthenticated/i.test(text)) {
    return {
      title: 'Google rejected the API key',
      detail:
        'The GEMINI_API_KEY on the render worker is missing, invalid, or lacks access to Veo. Nothing was charged. Check the key in Railway, then run this again.',
      actionUrl: 'https://aistudio.google.com/apikey',
      actionLabel: 'Check your API key',
    }
  }
  if (text.startsWith('SAFETY_BLOCKED:') || /safety|blocked|policy|prohibited/i.test(text)) {
    return {
      title: 'Google blocked this prompt',
      detail:
        'Veo refused to generate one of these shots on content-policy grounds. Nothing was charged for the blocked shot. Reword the shot prompt and try again.',
    }
  }
  if (text.startsWith('TIMEOUT:') || /timed out/i.test(text)) {
    return {
      title: 'Generation timed out',
      detail:
        'Google did not return a finished clip within 10 minutes. This is usually transient — try again. You are only charged for videos that actually generate.',
    }
  }
  return { title: 'Generation failed', detail: text.slice(0, 500) }
}

/**
 * Mirrors carousel_jobs/studio_jobs' shape closely — see docs/video-studio-trd.md §3a/§3d and
 * docs/video-studio-trd-phase2.md §3. `outline_json` and `engine`+`shots_json` are mutually
 * exclusive depending on `video_type`: a motion_graphics job only ever populates the former, a
 * generated_clips job only ever the latter.
 */
export interface VideoJob {
  id: string
  profile_id: string
  source_kind: StudioSourceKind
  source_signal_id: string | null
  topic: string
  platform: string
  aspect_ratio: AspectRatio
  video_type: VideoType
  status: VideoJobStatus
  outline_json: CarouselSlide[] | null
  copy_json: StudioCopy | null
  voiceover_script: string | null
  voiceover_url: string | null
  render_progress: RenderProgress | null
  final_video_url: string | null
  error_detail: string | null
  content_item_id: string | null
  engine: VideoEngine | null
  resolution: VideoResolution | null
  video_style_id: string | null
  shots_json: VideoShot[] | null
  estimated_cost_usd: number | null
  created_at: string
  updated_at: string
}

export async function listVideoJobs(profileId: string): Promise<VideoJob[]> {
  const { data, error } = await supabase
    .from('video_jobs')
    .select('*')
    .eq('profile_id', profileId)
    .order('created_at', { ascending: false })
    .limit(50)
  if (error) throw error
  return data as VideoJob[]
}

export async function getVideoJob(id: string): Promise<VideoJob | null> {
  const { data, error } = await supabase.from('video_jobs').select('*').eq('id', id).maybeSingle()
  if (error) throw error
  return data as VideoJob | null
}

/**
 * Fires ScalePods · Video Brief — one GPT-4o call writes the post copy AND, depending on
 * `videoType`, either a motion-graphics slide outline or a generated-clips shot storyboard
 * (+ an optional voiceover script), and responds synchronously with the inserted row.
 *
 * Nothing is generated or charged by Veo at this point — the brief step is a GPT call only, so
 * the whole storyboard (and its real price) is reviewable and editable before a single second of
 * video is paid for. That review gate is the entire point of splitting brief from generate.
 */
export async function generateVideoBrief(params: {
  profileId: string
  sourceKind: StudioSourceKind
  signalId?: string | null
  topic: string
  platform: string
  aspectRatio: AspectRatio
  wantsVoiceover: boolean
  videoType: VideoType
  /** motion_graphics only */
  slideCount?: number
  /** generated_clips only */
  engine?: VideoEngine
  resolution?: VideoResolution
  shotCount?: number
  durationS?: number
  videoStyleId?: string
  /** The chosen type's full cinematography direction — sent from the app rather than looked up in
   *  n8n so the wording stays versioned here (videoTypes.ts) and shows up in a diff when it
   *  changes. Same split AI Studio already uses for `styleDirection`. */
  styleDirection?: string
  /** The narrative arc GPT writes the shot list against. */
  styleArc?: string
}): Promise<VideoJob> {
  if (!GENERATION_ENABLED) throw new Error('Content generation is disabled (GENERATION_ENABLED=false)')
  if (params.videoType === 'generated_clips' && !VIDEO_GENERATION_ENABLED) {
    throw new Error('AI video generation is disabled (VIDEO_GENERATION_ENABLED=false)')
  }
  const res = await fireWebhook('sp-video-brief', {
    profileId: params.profileId,
    sourceKind: params.sourceKind,
    signalId: params.signalId ?? null,
    topic: params.topic,
    platform: params.platform,
    aspectRatio: params.aspectRatio,
    wantsVoiceover: params.wantsVoiceover,
    videoType: params.videoType,
    slideCount: params.slideCount,
    engine: params.engine,
    resolution: params.resolution,
    shotCount: params.shotCount,
    durationS: params.durationS,
    videoStyleId: params.videoStyleId,
    styleDirection: params.styleDirection,
    styleArc: params.styleArc,
  })
  return (await res.json()) as VideoJob
}

/** Persists outline/shots/copy/voiceover-script edits made in the review step, before spending. */
export async function updateVideoDraft(
  jobId: string,
  patch: {
    outline_json?: CarouselSlide[]
    shots_json?: VideoShot[]
    estimated_cost_usd?: number
    engine?: VideoEngine
    resolution?: VideoResolution
    copy_json?: StudioCopy
    voiceover_script?: string | null
  },
): Promise<void> {
  const { error } = await supabase.from('video_jobs').update(patch).eq('id', jobId)
  if (error) throw error
}

/**
 * Fires ScalePods · Video Render, which POSTs to the Railway worker's /render-video
 * (motion_graphics) or /generate-video (generated_clips) and returns immediately.
 *
 * For a generated_clips job this is the step that spends real money. The caller MUST have shown
 * the real figure and taken an explicit confirmation first (PRD §8 guardrail #3), and must not
 * call it above PER_VIDEO_CEILING_USD — that ceiling is re-checked here as a last line of
 * defence, since a UI-only guard is one refactor away from being bypassed.
 */
export async function triggerVideoRender(
  jobId: string,
  videoType: VideoType,
  estimatedCostUsd = 0,
): Promise<void> {
  if (!GENERATION_ENABLED) throw new Error('Content generation is disabled (GENERATION_ENABLED=false)')
  if (videoType === 'generated_clips') {
    if (!VIDEO_GENERATION_ENABLED) {
      throw new Error('AI video generation is disabled (VIDEO_GENERATION_ENABLED=false)')
    }
    if (estimatedCostUsd > PER_VIDEO_CEILING_USD) {
      throw new Error(
        `This video would cost ${formatUsdInr(estimatedCostUsd)}, over the $${PER_VIDEO_CEILING_USD} per-video limit. Remove a shot, shorten one, or pick a cheaper engine.`,
      )
    }
  }
  await fireWebhook('sp-video-render', { jobId })
}

/** Re-generates exactly ONE shot. The worker uploads the regenerated clip and the next full
 *  render reuses it rather than paying for it again — the whole reason per-shot regenerate is
 *  cheaper than re-rendering, mirroring AI Studio's per-slide regenerate economics. */
export async function regenerateVideoShot(jobId: string, shotIndex: number): Promise<void> {
  if (!VIDEO_GENERATION_ENABLED) throw new Error('AI video generation is disabled (VIDEO_GENERATION_ENABLED=false)')
  await fireWebhook('sp-video-regenerate-shot', { jobId, shotIndex })
}

export async function deleteVideoJob(jobId: string): Promise<void> {
  const { error } = await supabase.from('video_jobs').delete().eq('id', jobId)
  if (error) throw error
}

/** Links the job to the content_items row Send to Review produced — same purpose as
 *  markStudioJobUsed, so Video Studio can show "already sent to review" instead of letting the
 *  same finished video be pushed through twice. */
export async function markVideoJobUsed(jobId: string, contentItemId: string): Promise<void> {
  const { error } = await supabase.from('video_jobs').update({ content_item_id: contentItemId }).eq('id', jobId)
  if (error) throw error
}
