import { useState } from 'react'
import { useNavigate } from 'react-router-dom'
import { Sun, Moon, Sparkles, ArrowRight, ShieldCheck, User, Palette, Send } from 'lucide-react'
import { useAuth } from '../lib/auth'
import { toggleTheme, getTheme, type Theme, type Role, ROLE_ACCENT } from '../lib/theme'

const ROLES: { id: Role; label: string; icon: typeof User; blurb: string }[] = [
  { id: 'admin', label: 'Admin', icon: ShieldCheck, blurb: 'Run every engine' },
  { id: 'client', label: 'Client', icon: User, blurb: 'Review & approve' },
  { id: 'designer', label: 'Designer', icon: Palette, blurb: 'Edit creative' },
]

export default function Login() {
  const { signIn, role, setRole, sendReset } = useAuth()
  const [theme, setTheme] = useState<Theme>(getTheme())
  const [email, setEmail] = useState('marketing@scalepods.co')
  const [password, setPassword] = useState('')
  const [busy, setBusy] = useState(false)
  const [error, setError] = useState<string | null>(null)
  const [resetMode, setResetMode] = useState(false)
  const [resetSent, setResetSent] = useState(false)
  const [resetBusy, setResetBusy] = useState(false)
  const [resetError, setResetError] = useState<string | null>(null)
  const navigate = useNavigate()

  const logo = theme === 'dark' ? '/brand/logo-white.png' : '/brand/logo-black.png'

  async function onSubmit(e: React.FormEvent) {
    e.preventDefault()
    setBusy(true)
    setError(null)
    const { error } = await signIn(email, password)
    setBusy(false)
    if (error) setError(error)
    else navigate('/')
  }

  function openResetPanel() {
    if (!email) return setError('Enter your email first')
    setError(null)
    setResetMode(true)
  }

  function closeResetPanel() {
    setResetMode(false)
    setResetSent(false)
    setResetError(null)
  }

  async function sendResetLink() {
    setResetBusy(true)
    setResetError(null)
    const { error } = await sendReset(email)
    setResetBusy(false)
    if (error) setResetError(error)
    else setResetSent(true)
  }

  return (
    <div className="min-h-screen grid lg:grid-cols-2">
      {/* Brand panel — deliberately always the dark hero treatment regardless of the app's own
          light/dark theme (same idea as Vercel/Linear's login splash), not a themed surface. It
          used to sit on --alt-bg-green, whose light-mode value is a pale #E7F0DF — leaving the
          hardcoded white heading/logo on that background is how "light theme" turned into
          barely-legible white-on-white. Pinned to the actual dark value directly so this panel
          reads the same in both themes; --alt-bg-green itself stays theme-reactive for its one
          other real use (::selection). */}
      <div className="relative hidden lg:flex flex-col justify-between p-12 overflow-hidden bg-[#0B1A08]">
        {/* Looping ambient background (Pixabay, royalty-free, no attribution required —
            license: https://pixabay.com/service/license-summary/). Replaces the old animated
            blob-gradient decoration — a real loop already supplies the motion, so layering both
            would be too busy. The dark overlay is what keeps the heading readable regardless of
            what's happening in the footage; drop this whole block to go back to the flat color
            if the video doesn't earn its keep. */}
        <video
          className="absolute inset-0 w-full h-full object-cover"
          src="/brand/login-bg.mp4"
          autoPlay
          muted
          loop
          playsInline
        />
        <div className="absolute inset-0" style={{ background: 'rgba(11,26,8,0.72)' }} />
        <div className="absolute inset-0 grid-overlay opacity-40" />
        <div className="relative">
          <img src="/brand/logo-white.png" alt="ScalePods" className="h-7" />
        </div>
        <div className="relative">
          <div className="badge mb-5"><Sparkles size={13} /> Growth OS</div>
          <h1 className="text-5xl leading-[1.05] text-white max-w-lg">
            The marketing OS we <span className="accent-serif">run on ourselves</span>.
          </h1>
          <p className="text-white/60 mt-5 max-w-md">
            Brand knowledge → intelligence → strategy → content → publishing → analytics.
            Every screen is a live demo of what we build for you.
          </p>
        </div>
        <div className="relative badge badge-blue w-fit">
          <Sparkles size={12} /> Generated by ScalePods Growth OS AI
        </div>
      </div>

      {/* Form panel */}
      <div className="relative flex items-center justify-center p-6 sm:p-12">
        <button
          onClick={() => setTheme(toggleTheme())}
          className="btn-ghost absolute top-5 right-5 !p-2 !rounded-full"
          aria-label="Toggle theme"
        >
          {theme === 'dark' ? <Sun size={18} /> : <Moon size={18} />}
        </button>

        <div className="w-full max-w-sm">
          <img src={logo} alt="ScalePods" className="h-7 mb-8 lg:hidden" />
          <h2 className="text-2xl mb-1">Welcome back</h2>
          <p className="text-muted text-sm mb-6">Sign in to your Growth OS workspace.</p>

          {resetMode ? (
            <div>
              <div className="font-medium mb-1.5">Reset password</div>
              <p className="text-secondary text-sm mb-5 leading-relaxed">
                A password reset link will be sent to <b className="text-ink">{email}</b>.
              </p>

              {resetSent ? (
                <div
                  className="flex items-center gap-2.5 px-4 py-3 rounded-xl text-sm mb-4"
                  style={{ background: 'rgb(var(--accent-green-rgb) / 0.12)', border: '1px solid rgb(var(--accent-green-rgb) / 0.3)', color: 'var(--accent-green)' }}
                >
                  <Send size={16} className="shrink-0" />
                  <span>Reset link sent — check <b>{email}</b></span>
                </div>
              ) : (
                <>
                  {resetError && <div className="text-sm text-[var(--accent-orange)] mb-3">{resetError}</div>}
                  <button className="btn-primary w-full mb-3" onClick={sendResetLink} disabled={resetBusy}>
                    {resetBusy ? 'Sending…' : 'Send reset link'}
                  </button>
                </>
              )}

              <button onClick={closeResetPanel} className="text-sm text-muted hover:text-sage underline">
                ← Back to sign in
              </button>
            </div>
          ) : (
            <>
              {/* Role selector */}
              <div className="grid grid-cols-3 gap-2 mb-6">
                {ROLES.map((r) => {
                  const active = role === r.id
                  const Icon = r.icon
                  return (
                    <button
                      key={r.id}
                      type="button"
                      onClick={() => setRole(r.id)}
                      className={`panel !p-3 flex flex-col items-center gap-1 text-center transition-all ${
                        active ? 'ring-2' : 'opacity-70 hover:opacity-100'
                      }`}
                      style={active ? ({ '--tw-ring-color': ROLE_ACCENT[r.id] } as React.CSSProperties) : undefined}
                    >
                      <Icon size={18} style={{ color: ROLE_ACCENT[r.id] }} />
                      <span className="text-xs font-medium">{r.label}</span>
                      <span className="text-[10px] text-muted">{r.blurb}</span>
                    </button>
                  )
                })}
              </div>

              <form onSubmit={onSubmit} className="space-y-4">
                <div>
                  <label className="label">Email</label>
                  <input
                    className="input mt-1"
                    type="email"
                    value={email}
                    onChange={(e) => setEmail(e.target.value)}
                    autoComplete="username"
                    required
                  />
                </div>
                <div>
                  <div className="flex justify-between items-center">
                    <label className="label">Password</label>
                    <button type="button" onClick={openResetPanel} className="text-xs text-sage hover:underline">
                      Forgot?
                    </button>
                  </div>
                  <input
                    className="input mt-1"
                    type="password"
                    value={password}
                    onChange={(e) => setPassword(e.target.value)}
                    autoComplete="current-password"
                    required
                  />
                </div>

                {error && <div className="text-sm text-[var(--accent-orange)]">{error}</div>}

                <button type="submit" className="btn-primary w-full" disabled={busy}>
                  {busy ? 'Signing in…' : 'Sign in'} <ArrowRight size={16} />
                </button>
              </form>
            </>
          )}
        </div>
      </div>
    </div>
  )
}
