import { useState } from 'react'
import { useNavigate } from 'react-router-dom'
import { motion } from 'framer-motion'
import { Sun, Moon, Sparkles, ArrowRight, ShieldCheck, User, Palette } from 'lucide-react'
import { useAuth } from '../lib/auth'
import { toggleTheme, getTheme, type Theme, type Role, ROLE_ACCENT } from '../lib/theme'

const ROLES: { id: Role; label: string; icon: typeof User; blurb: string }[] = [
  { id: 'admin', label: 'Admin', icon: ShieldCheck, blurb: 'Run every engine' },
  { id: 'client', label: 'Client', icon: User, blurb: 'Review & approve' },
  { id: 'designer', label: 'Designer', icon: Palette, blurb: 'Edit creative' },
]

export default function Login() {
  const { signIn, role, setRole, sendReset } = useAuth()
  const [theme, setTheme] = useState<Theme>(getTheme())
  const [email, setEmail] = useState('marketing@scalepods.co')
  const [password, setPassword] = useState('')
  const [busy, setBusy] = useState(false)
  const [error, setError] = useState<string | null>(null)
  const [notice, setNotice] = useState<string | null>(null)
  const navigate = useNavigate()

  const logo = theme === 'dark' ? '/brand/logo-white.png' : '/brand/logo-black.png'

  async function onSubmit(e: React.FormEvent) {
    e.preventDefault()
    setBusy(true)
    setError(null)
    const { error } = await signIn(email, password)
    setBusy(false)
    if (error) setError(error)
    else navigate('/')
  }

  async function onReset() {
    if (!email) return setError('Enter your email first')
    const { error } = await sendReset(email)
    setError(error)
    if (!error) setNotice('Password reset email sent.')
  }

  return (
    <div className="min-h-screen grid lg:grid-cols-2">
      {/* Brand panel */}
      <div className="relative hidden lg:flex flex-col justify-between p-12 overflow-hidden bg-[var(--alt-bg-green)]">
        <div className="absolute inset-0 grid-overlay opacity-60" />
        <motion.div
          className="absolute -right-24 -top-24 h-96 w-96 rounded-full blur-3xl"
          style={{ background: 'radial-gradient(circle, rgba(177,217,151,0.35), transparent 70%)' }}
          animate={{ scale: [1, 1.15, 1], opacity: [0.5, 0.8, 0.5] }}
          transition={{ duration: 8, repeat: Infinity, ease: 'easeInOut' }}
        />
        <motion.div
          className="absolute -left-16 bottom-0 h-80 w-80 rounded-full blur-3xl"
          style={{ background: 'radial-gradient(circle, rgba(99,165,231,0.25), transparent 70%)' }}
          animate={{ scale: [1, 1.2, 1], opacity: [0.4, 0.7, 0.4] }}
          transition={{ duration: 10, repeat: Infinity, ease: 'easeInOut' }}
        />
        <div className="relative">
          <img src="/brand/logo-white.png" alt="ScalePods" className="h-7" />
        </div>
        <div className="relative">
          <div className="badge mb-5"><Sparkles size={13} /> Growth OS</div>
          <h1 className="text-5xl leading-[1.05] text-white max-w-lg">
            The marketing OS we <span className="accent-serif">run on ourselves</span>.
          </h1>
          <p className="text-white/60 mt-5 max-w-md">
            Brand knowledge → intelligence → strategy → content → publishing → analytics.
            Every screen is a live demo of what we build for you.
          </p>
        </div>
        <div className="relative badge badge-blue w-fit">
          <Sparkles size={12} /> Generated by ScalePods Growth OS AI
        </div>
      </div>

      {/* Form panel */}
      <div className="relative flex items-center justify-center p-6 sm:p-12">
        <button
          onClick={() => setTheme(toggleTheme())}
          className="btn-ghost absolute top-5 right-5 !p-2 !rounded-full"
          aria-label="Toggle theme"
        >
          {theme === 'dark' ? <Sun size={18} /> : <Moon size={18} />}
        </button>

        <div className="w-full max-w-sm">
          <img src={logo} alt="ScalePods" className="h-7 mb-8 lg:hidden" />
          <h2 className="text-2xl mb-1">Welcome back</h2>
          <p className="text-muted text-sm mb-6">Sign in to your Growth OS workspace.</p>

          {/* Role selector */}
          <div className="grid grid-cols-3 gap-2 mb-6">
            {ROLES.map((r) => {
              const active = role === r.id
              const Icon = r.icon
              return (
                <button
                  key={r.id}
                  type="button"
                  onClick={() => setRole(r.id)}
                  className={`panel !p-3 flex flex-col items-center gap-1 text-center transition-all ${
                    active ? 'ring-2' : 'opacity-70 hover:opacity-100'
                  }`}
                  style={active ? ({ '--tw-ring-color': ROLE_ACCENT[r.id] } as React.CSSProperties) : undefined}
                >
                  <Icon size={18} style={{ color: ROLE_ACCENT[r.id] }} />
                  <span className="text-xs font-medium">{r.label}</span>
                  <span className="text-[10px] text-muted">{r.blurb}</span>
                </button>
              )
            })}
          </div>

          <form onSubmit={onSubmit} className="space-y-4">
            <div>
              <label className="label">Email</label>
              <input
                className="input mt-1"
                type="email"
                value={email}
                onChange={(e) => setEmail(e.target.value)}
                autoComplete="username"
                required
              />
            </div>
            <div>
              <div className="flex justify-between items-center">
                <label className="label">Password</label>
                <button type="button" onClick={onReset} className="text-xs text-sage hover:underline">
                  Forgot?
                </button>
              </div>
              <input
                className="input mt-1"
                type="password"
                value={password}
                onChange={(e) => setPassword(e.target.value)}
                autoComplete="current-password"
                required
              />
            </div>

            {error && <div className="text-sm text-[var(--accent-orange)]">{error}</div>}
            {notice && <div className="text-sm text-sage">{notice}</div>}

            <button type="submit" className="btn-primary w-full" disabled={busy}>
              {busy ? 'Signing in…' : 'Sign in'} <ArrowRight size={16} />
            </button>
          </form>
        </div>
      </div>
    </div>
  )
}
